import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ErrorBoundary } from "@/components/layout/ErrorBoundary";
import { KpiCard } from "@/components/dashboard/KpiCard";
import { RevenueOverTime } from "@/components/charts/RevenueOverTime";
import { SpendRevenueScatter } from "@/components/charts/SpendRevenueScatter";
import { TopCampaigns } from "@/components/charts/TopCampaigns";
import { PlatformCompare } from "@/components/charts/PlatformCompare";
import { DeviceDistribution } from "@/components/charts/DeviceDistribution";
import { CountryRanking } from "@/components/charts/CountryRanking";
import { useSummary } from "@/hooks/use-analytics";
import { useAnalyticsFilters } from "@/store/filters";
import {
  formatCurrency, formatCompact, formatPercent, formatRoas,
} from "@/utils/format";
import {
  Activity, DollarSign, Eye, MousePointerClick, Target, TrendingUp, Wallet, Zap,
} from "lucide-react";
import type { FilterState } from "@/types/analytics";


function Inner() {
  const filters = useAnalyticsFilters();
  const { data, isFetching } = useSummary(filters);

  const kpi = data?.kpi;
  const deltas = data?.deltaPct ?? {};

  const cards = [
    { label: "Impressions", value: formatCompact(kpi?.impressions ?? 0), delta: deltas.impressions ?? null, icon: <Eye className="size-3" />, hint: "Total ad impressions served in the selected window.", good: true },
    { label: "Clicks", value: formatCompact(kpi?.clicks ?? 0), delta: deltas.clicks ?? null, icon: <MousePointerClick className="size-3" />, hint: "Total clicks across all campaigns and platforms.", good: true },
    { label: "Conversions", value: formatCompact(kpi?.conversions ?? 0), delta: deltas.conversions ?? null, icon: <Target className="size-3" />, hint: "Completed conversions attributed to ad clicks.", good: true },
    { label: "Spend", value: formatCurrency(kpi?.spend ?? 0), delta: deltas.spend ?? null, icon: <Wallet className="size-3" />, hint: "Total media spend. Rising spend is neutral — watch ROAS.", good: false },
    { label: "Revenue", value: formatCurrency(kpi?.revenue ?? 0), delta: deltas.revenue ?? null, icon: <DollarSign className="size-3" />, hint: "Attributed revenue generated by paid campaigns.", good: true },
    { label: "Avg CTR", value: formatPercent(kpi?.avgCtr ?? 0), delta: deltas.ctr ?? null, icon: <Activity className="size-3" />, hint: "Click-through rate = clicks ÷ impressions, volume-weighted.", good: true },
    { label: "Avg CVR", value: formatPercent(kpi?.avgConversionRate ?? 0), delta: deltas.conversionRate ?? null, icon: <Zap className="size-3" />, hint: "Conversion rate = conversions ÷ clicks, volume-weighted.", good: true },
    { label: "ROAS", value: formatRoas(kpi?.roas ?? 0), delta: deltas.roas ?? null, icon: <TrendingUp className="size-3" />, hint: "Return on ad spend = revenue ÷ spend. Above 3x is typically healthy.", good: true },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-lg font-semibold tracking-tight">Overview</h2>
          <p className="text-xs text-muted-foreground">
            {isFetching ? "Aggregating…" : `${formatCompact(kpi?.rowCount ?? 0)} records in view`}
          </p>
        </div>
        <Button variant="outline" size="sm" asChild>
          <a href="/explorer">Open Data Explorer</a>
        </Button>
      </div>

      <section aria-label="Key performance indicators" className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {cards.map((c) => (
          <KpiCard
            key={c.label}
            label={c.label}
            value={c.value}
            deltaPct={c.delta}
            goodWhenUp={c.good}
            hint={c.hint}
            loading={!data && isFetching}
            icon={c.icon}
          />
        ))}
      </section>

      <RevenueOverTimeWithToggle />

      <div className="grid gap-4 lg:grid-cols-2">
        <ErrorBoundary><TopCampaigns /></ErrorBoundary>
        <ErrorBoundary><PlatformCompare /></ErrorBoundary>
        <ErrorBoundary><SpendRevenueScatter /></ErrorBoundary>
        <ErrorBoundary><DeviceDistribution /></ErrorBoundary>
      </div>

      <ErrorBoundary><CountryRanking /></ErrorBoundary>
    </div>
  );
}

function RevenueOverTimeWithToggle() {
  const [granularity, setGranularity] = useState<"day" | "week">("day");
  return (
    <div className="relative">
      <RevenueOverTime granularity={granularity} />
      <div className="absolute right-4 top-[52px] z-10 flex gap-1 rounded-lg border bg-background p-0.5">
        <button
          onClick={() => setGranularity("day")}
          aria-pressed={granularity === "day"}
          className={cnToggle(granularity === "day")}
        >
          Daily
        </button>
        <button
          onClick={() => setGranularity("week")}
          aria-pressed={granularity === "week"}
          className={cnToggle(granularity === "week")}
        >
          Weekly
        </button>
      </div>
    </div>
  );
}

function cnToggle(active: boolean): string {
  return `rounded-md px-2 py-0.5 text-[11px] font-medium ${active ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`;
}

export default Inner;
